import sanitizeHtml from 'sanitize-html';

const allowedTags = [
  'p',
  'br',
  'strong',
  'b',
  'em',
  'i',
  'u',
  's',
  'blockquote',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'ul',
  'ol',
  'li',
  'a',
  'img',
  'code',
  'pre',
  'hr',
  'span',
  'div',
  'style',
  'section',
  'article',
  'header',
  'footer',
  'nav',
  'aside',
  'main',
  'table',
  'thead',
  'tbody',
  'tfoot',
  'tr',
  'th',
  'td',
  'caption',
];

const allowedAttributes: sanitizeHtml.IOptions['allowedAttributes'] = {
  a: ['href', 'name', 'target', 'rel', 'title'],
  img: ['src', 'alt', 'title', 'width', 'height', 'loading'],
  '*': ['style', 'class', 'id'],
};

const allowedStyles: sanitizeHtml.IOptions['allowedStyles'] = {
  '*': {
    color: [/^#[0-9a-fA-F]{3,8}$/, /^rgb(a)?\(/, /^hsl(a)?\(/],
    'background-color': [/^#[0-9a-fA-F]{3,8}$/, /^rgb(a)?\(/, /^hsl(a)?\(/],
    background: [/^.*$/],
    'background-image': [/^.*$/],
    'background-size': [/^.*$/],
    'background-position': [/^.*$/],
    display: [/^.*$/],
    position: [/^.*$/],
    top: [/^.*$/],
    right: [/^.*$/],
    bottom: [/^.*$/],
    left: [/^.*$/],
    inset: [/^.*$/],
    'z-index': [/^.*$/],
    width: [/^.*$/],
    height: [/^.*$/],
    'min-width': [/^.*$/],
    'min-height': [/^.*$/],
    'max-width': [/^.*$/],
    'max-height': [/^.*$/],
    margin: [/^.*$/],
    'margin-top': [/^.*$/],
    'margin-right': [/^.*$/],
    'margin-bottom': [/^.*$/],
    'margin-left': [/^.*$/],
    padding: [/^.*$/],
    'padding-top': [/^.*$/],
    'padding-right': [/^.*$/],
    'padding-bottom': [/^.*$/],
    'padding-left': [/^.*$/],
    gap: [/^.*$/],
    'row-gap': [/^.*$/],
    'column-gap': [/^.*$/],
    flex: [/^.*$/],
    'flex-basis': [/^.*$/],
    'flex-grow': [/^.*$/],
    'flex-shrink': [/^.*$/],
    'flex-direction': [/^.*$/],
    'flex-wrap': [/^.*$/],
    'align-items': [/^.*$/],
    'align-content': [/^.*$/],
    'justify-content': [/^.*$/],
    'justify-items': [/^.*$/],
    'text-align': [/^(left|right|center|justify)$/],
    'font-size': [/^\d+(\.\d+)?(px|rem|em|%)$/],
    'font-family': [/^.*$/],
    'font-weight': [/^.*$/],
    'font-style': [/^.*$/],
    'line-height': [/^.*$/],
    'letter-spacing': [/^.*$/],
    'text-decoration': [/^.*$/],
    'text-transform': [/^.*$/],
    'white-space': [/^.*$/],
    border: [/^.*$/],
    'border-top': [/^.*$/],
    'border-right': [/^.*$/],
    'border-bottom': [/^.*$/],
    'border-left': [/^.*$/],
    'border-width': [/^.*$/],
    'border-style': [/^.*$/],
    'border-color': [/^.*$/],
    'border-radius': [/^.*$/],
    'box-shadow': [/^.*$/],
    opacity: [/^.*$/],
    overflow: [/^.*$/],
    'overflow-x': [/^.*$/],
    'overflow-y': [/^.*$/],
    'object-fit': [/^.*$/],
    'object-position': [/^.*$/],
    transform: [/^.*$/],
    transition: [/^.*$/],
    cursor: [/^.*$/],
    outline: [/^.*$/],
    filter: [/^.*$/],
    mask: [/^.*$/],
    'clip-path': [/^.*$/],
    'grid-template-columns': [/^.*$/],
    'grid-template-rows': [/^.*$/],
    'grid-column': [/^.*$/],
    'grid-row': [/^.*$/],
    'aspect-ratio': [/^.*$/],
  },
};

export function sanitizeBlogHtml(html: string): string {
  if (!html) return '';

  return sanitizeHtml(html, {
    allowedTags,
    allowedAttributes,
    allowedStyles,
    allowedSchemes: ['http', 'https', 'mailto'],
    allowedSchemesByTag: {
      img: ['http', 'https'],
    },
    transformTags: {
      a: (tagName, attribs) => {
        const target = attribs.target || undefined;
        return {
          tagName,
          attribs: {
            ...attribs,
            rel: 'noopener noreferrer',
            ...(target === '_blank' ? { target: '_blank' } : {}),
          },
        };
      },
    },
    parser: {
      lowerCaseTags: true,
      lowerCaseAttributeNames: true,
    },
  });
}

export function stripHtmlTags(html: string): string {
  if (!html) return '';
  // Use sanitize-html to remove all tags but preserve text content
  return sanitizeHtml(html, { allowedTags: [], allowedAttributes: {} }).trim();
}
